# NOTE: Generated By HttpRunner v3.1.4
# FROM: post.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCasePost(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/login")
            .post("http://127.0.0.1:8080/login")
            .with_headers(
                **{
                    "Content-Type": "application/x-www-form-urlencoded",
                }
            )
            .with_data('username=admin&password=123456')
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json")
            .assert_equal("body.message", "login success")
        ),
    ]


if __name__ == "__main__":
    TestCasePost().test_start()
